In [1]:
import numpy as np

In [12]:
x = np.array( [ [1,2,3], 
                [4,5,6] ] )
print(x, x.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [8]:
print(x[0], x[0].shape)

[1 2 3] (3,)


In [13]:
print(x[0, 1], x[0][1])
print(x[:, 1])
print(x[0, :], x[0])

2 2
[2 5]
[1 2 3] [1 2 3]


In [17]:
print(x.shape)
print(x)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [20]:
y = x.reshape( (3,2))

print(y.shape)
print(y)

z = x.reshape(6) 
print(z.shape)
print(z)


z2 = x.reshape( (6,1) ) 
print(z2.shape)
print(z2)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(6,)
[1 2 3 4 5 6]
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [25]:
x = np.linspace(0, 1, 100)
print(x)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [28]:
x = np.zeros(10)
print(x)

x = np.zeros( (10, 10) )
print(x)

x = np.ones( (10, 5))
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
x = np.linspace(1, 10, 10)

print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [34]:
print(x[:])
print(x[1:5])

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2. 3. 4. 5.]


In [36]:
print(x[1:10:3])

[2. 5. 8.]


In [42]:
x = np.linspace(1, 10, 10)
y = np.linspace(1, 10, 10)

_, g = np.meshgrid(x, y)

print(g, g.shape)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]] (10, 10)


In [44]:
print( g[5:9:2, 1:10:3])

[[6. 6. 6.]
 [8. 8. 8.]]


In [54]:
x = np.array( [1, -1] )
y = np.array( [2, 4])

print(x, y)

[ 1 -1] [2 4]


In [55]:
print(x + y)

[3 3]


In [56]:
print(x - y)

[-1 -5]


In [57]:
print( x * y)

[ 2 -4]


In [58]:
print( x / y)

[ 0.5  -0.25]


In [60]:
print( 2 * x)
print( np.sin( x) )

[ 2 -2]
[ 0.84147098 -0.84147098]


In [62]:
print(x.min() )
print(x.max() )
print(x.sum() )

-1
1
0


In [67]:
x = np.random.random( (2, 6))

In [68]:
print(x)

[[0.6565345  0.00885799 0.01556393 0.82699544 0.32158334 0.13587482]
 [0.12118161 0.61466038 0.42201428 0.87848697 0.66205721 0.10602193]]


In [70]:
y = x.reshape( (3,4), order="C")
print(y)

z = x.reshape( (3,4), order="F")
print(z)

[[0.6565345  0.00885799 0.01556393 0.82699544]
 [0.32158334 0.13587482 0.12118161 0.61466038]
 [0.42201428 0.87848697 0.66205721 0.10602193]]
[[0.6565345  0.61466038 0.82699544 0.66205721]
 [0.12118161 0.01556393 0.87848697 0.13587482]
 [0.00885799 0.42201428 0.32158334 0.10602193]]


In [75]:
print("=========")
print(x)
print("=========")
print(x[0])
print("=========")
print(x.min(axis=0))
print("=========")
print(x.min(axis=1))

[[0.6565345  0.00885799 0.01556393 0.82699544 0.32158334 0.13587482]
 [0.12118161 0.61466038 0.42201428 0.87848697 0.66205721 0.10602193]]
[0.6565345  0.00885799 0.01556393 0.82699544 0.32158334 0.13587482]
[0.12118161 0.00885799 0.01556393 0.82699544 0.32158334 0.10602193]
[0.00885799 0.10602193]
